name: CI

on:
  pull_request:
    branches: [ main, release* ]

  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: SetUp JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Unit Tests
        run: ./gradlew test --stacktrace
        
  instrumented-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: SetUp JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

        
  build-and-generate-apk:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: SetUp JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
      - name: Build Debug 
        run: ./gradlew assembleDebug
      - name: Upload APK on Github Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Generate APK
          path: app/build/outputs/apk/debug/app-debug.apk
